image: gitpod/workspace-full

tasks:
  - init: |
      docker compose -f docker-compose.yml up -d
      sleep 60
    command: |
      gp ports expose 8080

ports:
  - port: 8080
    onOpen: open-preview
